//
//  File 2.swift
//
//
//  Created by Coen ten Thije Boonkkamp on 19/07/2024.
//

import Dependencies
import Foundation
import Language

extension Translated {
    public init(
        _ default: A
    ) {
        self = .init(default: `default`, dictionary: [:])
    }
}

extension Translated {
    public init(
        _ closure: (Language) -> A
    ) {
        @Dependency(\.languages) var languages

        self = .init(
            default: closure(.english),
            dictionary: Dictionary(uniqueKeysWithValues: languages.map { ($0, closure($0)) })
        )
    }
}

extension Translated {
    public init(
        _ `default`: A,
        abkhazian: A? = nil,
        afar: A? = nil,
        afrikaans: A? = nil,
        akan: A? = nil,
        albanian: A? = nil,
        amharic: A? = nil,
        arabic: A? = nil,
        aragonese: A? = nil,
        armenian: A? = nil,
        assamese: A? = nil,
        auEnglish: A? = nil,
        avaric: A? = nil,
        avestan: A? = nil,
        aymara: A? = nil,
        azerbaijani: A? = nil,
        bambara: A? = nil,
        bashkir: A? = nil,
        basque: A? = nil,
        belarusian: A? = nil,
        bengali: A? = nil,
        bihari: A? = nil,
        bislama: A? = nil,
        bosnian: A? = nil,
        breton: A? = nil,
        bulgarian: A? = nil,
        burmese: A? = nil,
        caEnglish: A? = nil,
        catalan: A? = nil,
        chamorro: A? = nil,
        chechen: A? = nil,
        chinese: A? = nil,
        chuvash: A? = nil,
        cornish: A? = nil,
        corsican: A? = nil,
        cree: A? = nil,
        croatian: A? = nil,
        czech: A? = nil,
        danish: A? = nil,
        dutch: A? = nil,
        dzongkha: A? = nil,
        english: A? = nil,
        esperanto: A? = nil,
        estonian: A? = nil,
        ewe: A? = nil,
        faroese: A? = nil,
        fijian: A? = nil,
        finnish: A? = nil,
        french: A? = nil,
        galician: A? = nil,
        gaelicScottish: A? = nil,
        georgian: A? = nil,
        german: A? = nil,
        greek: A? = nil,
        guarani: A? = nil,
        gujarati: A? = nil,
        haitianCreole: A? = nil,
        hausa: A? = nil,
        hebrew: A? = nil,
        herero: A? = nil,
        hindi: A? = nil,
        hiriMotu: A? = nil,
        hungarian: A? = nil,
        icelandic: A? = nil,
        ido: A? = nil,
        igbo: A? = nil,
        indonesian: A? = nil,
        interlingua: A? = nil,
        interlingue: A? = nil,
        inuktitut: A? = nil,
        inupiak: A? = nil,
        irish: A? = nil,
        italian: A? = nil,
        japanese: A? = nil,
        javanese: A? = nil,
        kannada: A? = nil,
        kanuri: A? = nil,
        kashmiri: A? = nil,
        kazakh: A? = nil,
        khmer: A? = nil,
        kikuyu: A? = nil,
        kinyarwanda: A? = nil,
        kirundi: A? = nil,
        komi: A? = nil,
        kongo: A? = nil,
        korean: A? = nil,
        kurdish: A? = nil,
        kwanyama: A? = nil,
        kyrgyz: A? = nil,
        lao: A? = nil,
        latin: A? = nil,
        latvian: A? = nil,
        limburgish: A? = nil,
        lingala: A? = nil,
        lithuanian: A? = nil,
        lugaKatanga: A? = nil,
        luxembourgish: A? = nil,
        macedonian: A? = nil,
        malagasy: A? = nil,
        malay: A? = nil,
        malayalam: A? = nil,
        maltese: A? = nil,
        manx: A? = nil,
        maori: A? = nil,
        marathi: A? = nil,
        marshallese: A? = nil,
        moldavian: A? = nil,
        mongolian: A? = nil,
        nauru: A? = nil,
        navajo: A? = nil,
        ndonga: A? = nil,
        nepali: A? = nil,
        northernNdebele: A? = nil,
        norwegian: A? = nil,
        norwegianBokmål: A? = nil,
        norwegianNynorsk: A? = nil,
        occitan: A? = nil,
        ojibwe: A? = nil,
        oriya: A? = nil,
        oromo: A? = nil,
        ossetian: A? = nil,
        pāli: A? = nil,
        persian: A? = nil,
        polish: A? = nil,
        portuguese: A? = nil,
        punjabi: A? = nil,
        quechua: A? = nil,
        romanian: A? = nil,
        romansh: A? = nil,
        russian: A? = nil,
        sami: A? = nil,
        samoan: A? = nil,
        sango: A? = nil,
        sanskrit: A? = nil,
        serbian: A? = nil,
        serboCroatian: A? = nil,
        sesotho: A? = nil,
        setswana: A? = nil,
        shona: A? = nil,
        sindhi: A? = nil,
        sinhalese: A? = nil,
        slovak: A? = nil,
        slovenian: A? = nil,
        somali: A? = nil,
        southernNdebele: A? = nil,
        spanish: A? = nil,
        sundanese: A? = nil,
        swahili: A? = nil,
        swati: A? = nil,
        swedish: A? = nil,
        tagalog: A? = nil,
        tahitian: A? = nil,
        tajik: A? = nil,
        tamil: A? = nil,
        tatar: A? = nil,
        telugu: A? = nil,
        thai: A? = nil,
        tibetan: A? = nil,
        tigrinya: A? = nil,
        tonga: A? = nil,
        tsonga: A? = nil,
        turkish: A? = nil,
        turkmen: A? = nil,
        twi: A? = nil,
        ukEnglish: A? = nil,
        ukrainian: A? = nil,
        urdu: A? = nil,
        usEnglish: A? = nil,
        uyghur: A? = nil,
        uzbek: A? = nil,
        venda: A? = nil,
        vietnamese: A? = nil,
        volapük: A? = nil,
        wallon: A? = nil,
        welsh: A? = nil,
        westernFrisian: A? = nil,
        wolof: A? = nil,
        xhosa: A? = nil,
        yoruba: A? = nil,
        zulu: A? = nil
    ) {
        @Dependency(\.languages) var languages

        self = .init(
            default: `default`,
            dictionary: [
                .abkhazian: languages.contains(.abkhazian) ? abkhazian : nil,
                .afar: languages.contains(.afar) ? afar : nil,
                .afrikaans: languages.contains(.afrikaans) ? afrikaans : nil,
                .akan: languages.contains(.akan) ? akan : nil,
                .albanian: languages.contains(.albanian) ? albanian : nil,
                .amharic: languages.contains(.amharic) ? amharic : nil,
                .arabic: languages.contains(.arabic) ? arabic : nil,
                .aragonese: languages.contains(.aragonese) ? aragonese : nil,
                .armenian: languages.contains(.armenian) ? armenian : nil,
                .assamese: languages.contains(.assamese) ? assamese : nil,
                .auEnglish: languages.contains(.auEnglish) ? auEnglish : nil,
                .avaric: languages.contains(.avaric) ? avaric : nil,
                .avestan: languages.contains(.avestan) ? avestan : nil,
                .aymara: languages.contains(.aymara) ? aymara : nil,
                .azerbaijani: languages.contains(.azerbaijani) ? azerbaijani : nil,
                .bambara: languages.contains(.bambara) ? bambara : nil,
                .bashkir: languages.contains(.bashkir) ? bashkir : nil,
                .basque: languages.contains(.basque) ? basque : nil,
                .belarusian: languages.contains(.belarusian) ? belarusian : nil,
                .bengali: languages.contains(.bengali) ? bengali : nil,
                .bihari: languages.contains(.bihari) ? bihari : nil,
                .bislama: languages.contains(.bislama) ? bislama : nil,
                .bosnian: languages.contains(.bosnian) ? bosnian : nil,
                .breton: languages.contains(.breton) ? breton : nil,
                .bulgarian: languages.contains(.bulgarian) ? bulgarian : nil,
                .burmese: languages.contains(.burmese) ? burmese : nil,
                .catalan: languages.contains(.catalan) ? catalan : nil,
                .caEnglish: languages.contains(.caEnglish) ? caEnglish : nil,
                .chamorro: languages.contains(.chamorro) ? chamorro : nil,
                .chechen: languages.contains(.chechen) ? chechen : nil,
                .chinese: languages.contains(.chinese) ? chinese : nil,
                .chuvash: languages.contains(.chuvash) ? chuvash : nil,
                .cornish: languages.contains(.cornish) ? cornish : nil,
                .corsican: languages.contains(.corsican) ? corsican : nil,
                .cree: languages.contains(.cree) ? cree : nil,
                .croatian: languages.contains(.croatian) ? croatian : nil,
                .czech: languages.contains(.czech) ? czech : nil,
                .danish: languages.contains(.danish) ? danish : nil,
                .dutch: languages.contains(.dutch) ? dutch : nil,
                .dzongkha: languages.contains(.dzongkha) ? dzongkha : nil,
                .english: languages.contains(.english) ? english : nil,
                .esperanto: languages.contains(.esperanto) ? esperanto : nil,
                .estonian: languages.contains(.estonian) ? estonian : nil,
                .ewe: languages.contains(.ewe) ? ewe : nil,
                .faroese: languages.contains(.faroese) ? faroese : nil,
                .fijian: languages.contains(.fijian) ? fijian : nil,
                .finnish: languages.contains(.finnish) ? finnish : nil,
                .french: languages.contains(.french) ? french : nil,
                .galician: languages.contains(.galician) ? galician : nil,
                .gaelicScottish: languages.contains(.gaelicScottish) ? gaelicScottish : nil,
                .georgian: languages.contains(.georgian) ? georgian : nil,
                .german: languages.contains(.german) ? german : nil,
                .greek: languages.contains(.greek) ? greek : nil,
                .guarani: languages.contains(.guarani) ? guarani : nil,
                .gujarati: languages.contains(.gujarati) ? gujarati : nil,
                .haitianCreole: languages.contains(.haitianCreole) ? haitianCreole : nil,
                .hausa: languages.contains(.hausa) ? hausa : nil,
                .hebrew: languages.contains(.hebrew) ? hebrew : nil,
                .herero: languages.contains(.herero) ? herero : nil,
                .hindi: languages.contains(.hindi) ? hindi : nil,
                .hiriMotu: languages.contains(.hiriMotu) ? hiriMotu : nil,
                .hungarian: languages.contains(.hungarian) ? hungarian : nil,
                .icelandic: languages.contains(.icelandic) ? icelandic : nil,
                .ido: languages.contains(.ido) ? ido : nil,
                .igbo: languages.contains(.igbo) ? igbo : nil,
                .indonesian: languages.contains(.indonesian) ? indonesian : nil,
                .interlingua: languages.contains(.interlingua) ? interlingua : nil,
                .interlingue: languages.contains(.interlingue) ? interlingue : nil,
                .inuktitut: languages.contains(.inuktitut) ? inuktitut : nil,
                .inupiak: languages.contains(.inupiak) ? inupiak : nil,
                .irish: languages.contains(.irish) ? irish : nil,
                .italian: languages.contains(.italian) ? italian : nil,
                .japanese: languages.contains(.japanese) ? japanese : nil,
                .javanese: languages.contains(.javanese) ? javanese : nil,
                .kannada: languages.contains(.kannada) ? kannada : nil,
                .kanuri: languages.contains(.kanuri) ? kanuri : nil,
                .kashmiri: languages.contains(.kashmiri) ? kashmiri : nil,
                .kazakh: languages.contains(.kazakh) ? kazakh : nil,
                .khmer: languages.contains(.khmer) ? khmer : nil,
                .kikuyu: languages.contains(.kikuyu) ? kikuyu : nil,
                .kinyarwanda: languages.contains(.kinyarwanda) ? kinyarwanda : nil,
                .kirundi: languages.contains(.kirundi) ? kirundi : nil,
                .komi: languages.contains(.komi) ? komi : nil,
                .kongo: languages.contains(.kongo) ? kongo : nil,
                .korean: languages.contains(.korean) ? korean : nil,
                .kurdish: languages.contains(.kurdish) ? kurdish : nil,
                .kwanyama: languages.contains(.kwanyama) ? kwanyama : nil,
                .kyrgyz: languages.contains(.kyrgyz) ? kyrgyz : nil,
                .lao: languages.contains(.lao) ? lao : nil,
                .latin: languages.contains(.latin) ? latin : nil,
                .latvian: languages.contains(.latvian) ? latvian : nil,
                .limburgish: languages.contains(.limburgish) ? limburgish : nil,
                .lingala: languages.contains(.lingala) ? lingala : nil,
                .lithuanian: languages.contains(.lithuanian) ? lithuanian : nil,
                .lugaKatanga: languages.contains(.lugaKatanga) ? lugaKatanga : nil,
                .luxembourgish: languages.contains(.luxembourgish) ? luxembourgish : nil,
                .macedonian: languages.contains(.macedonian) ? macedonian : nil,
                .malagasy: languages.contains(.malagasy) ? malagasy : nil,
                .malay: languages.contains(.malay) ? malay : nil,
                .malayalam: languages.contains(.malayalam) ? malayalam : nil,
                .maltese: languages.contains(.maltese) ? maltese : nil,
                .manx: languages.contains(.manx) ? manx : nil,
                .maori: languages.contains(.maori) ? maori : nil,
                .marathi: languages.contains(.marathi) ? marathi : nil,
                .marshallese: languages.contains(.marshallese) ? marshallese : nil,
                .moldavian: languages.contains(.moldavian) ? moldavian : nil,
                .mongolian: languages.contains(.mongolian) ? mongolian : nil,
                .nauru: languages.contains(.nauru) ? nauru : nil,
                .navajo: languages.contains(.navajo) ? navajo : nil,
                .ndonga: languages.contains(.ndonga) ? ndonga : nil,
                .nepali: languages.contains(.nepali) ? nepali : nil,
                .northernNdebele: languages.contains(.northernNdebele) ? northernNdebele : nil,
                .norwegian: languages.contains(.norwegian) ? norwegian : nil,
                .norwegianBokmål: languages.contains(.norwegianBokmål) ? norwegianBokmål : nil,
                .norwegianNynorsk: languages.contains(.norwegianNynorsk) ? norwegianNynorsk : nil,
                .occitan: languages.contains(.occitan) ? occitan : nil,
                .ojibwe: languages.contains(.ojibwe) ? ojibwe : nil,
                .oriya: languages.contains(.oriya) ? oriya : nil,
                .oromo: languages.contains(.oromo) ? oromo : nil,
                .ossetian: languages.contains(.ossetian) ? ossetian : nil,
                .pāli: languages.contains(.pāli) ? pāli : nil,
                .persian: languages.contains(.persian) ? persian : nil,
                .polish: languages.contains(.polish) ? polish : nil,
                .portuguese: languages.contains(.portuguese) ? portuguese : nil,
                .punjabi: languages.contains(.punjabi) ? punjabi : nil,
                .quechua: languages.contains(.quechua) ? quechua : nil,
                .romanian: languages.contains(.romanian) ? romanian : nil,
                .romansh: languages.contains(.romansh) ? romansh : nil,
                .russian: languages.contains(.russian) ? russian : nil,
                .sami: languages.contains(.sami) ? sami : nil,
                .samoan: languages.contains(.samoan) ? samoan : nil,
                .sango: languages.contains(.sango) ? sango : nil,
                .sanskrit: languages.contains(.sanskrit) ? sanskrit : nil,
                .serbian: languages.contains(.serbian) ? serbian : nil,
                .serboCroatian: languages.contains(.serboCroatian) ? serboCroatian : nil,
                .sesotho: languages.contains(.sesotho) ? sesotho : nil,
                .setswana: languages.contains(.setswana) ? setswana : nil,
                .shona: languages.contains(.shona) ? shona : nil,
                .sindhi: languages.contains(.sindhi) ? sindhi : nil,
                .sinhalese: languages.contains(.sinhalese) ? sinhalese : nil,
                .slovak: languages.contains(.slovak) ? slovak : nil,
                .slovenian: languages.contains(.slovenian) ? slovenian : nil,
                .somali: languages.contains(.somali) ? somali : nil,
                .southernNdebele: languages.contains(.southernNdebele) ? southernNdebele : nil,
                .spanish: languages.contains(.spanish) ? spanish : nil,
                .sundanese: languages.contains(.sundanese) ? sundanese : nil,
                .swahili: languages.contains(.swahili) ? swahili : nil,
                .swati: languages.contains(.swati) ? swati : nil,
                .swedish: languages.contains(.swedish) ? swedish : nil,
                .tagalog: languages.contains(.tagalog) ? tagalog : nil,
                .tahitian: languages.contains(.tahitian) ? tahitian : nil,
                .tajik: languages.contains(.tajik) ? tajik : nil,
                .tamil: languages.contains(.tamil) ? tamil : nil,
                .tatar: languages.contains(.tatar) ? tatar : nil,
                .telugu: languages.contains(.telugu) ? telugu : nil,
                .thai: languages.contains(.thai) ? thai : nil,
                .tibetan: languages.contains(.tibetan) ? tibetan : nil,
                .tigrinya: languages.contains(.tigrinya) ? tigrinya : nil,
                .tonga: languages.contains(.tonga) ? tonga : nil,
                .tsonga: languages.contains(.tsonga) ? tsonga : nil,
                .turkish: languages.contains(.turkish) ? turkish : nil,
                .turkmen: languages.contains(.turkmen) ? turkmen : nil,
                .twi: languages.contains(.twi) ? twi : nil,
                .ukEnglish: languages.contains(.ukEnglish) ? ukEnglish : nil,
                .ukrainian: languages.contains(.ukrainian) ? ukrainian : nil,
                .urdu: languages.contains(.urdu) ? urdu : nil,
                .usEnglish: languages.contains(.usEnglish) ? usEnglish : nil,
                .uyghur: languages.contains(.uyghur) ? uyghur : nil,
                .uzbek: languages.contains(.uzbek) ? uzbek : nil,
                .venda: languages.contains(.venda) ? venda : nil,
                .vietnamese: languages.contains(.vietnamese) ? vietnamese : nil,
                .volapük: languages.contains(.volapük) ? volapük : nil,
                .wallon: languages.contains(.wallon) ? wallon : nil,
                .welsh: languages.contains(.welsh) ? welsh : nil,
                .westernFrisian: languages.contains(.westernFrisian) ? westernFrisian : nil,
                .wolof: languages.contains(.wolof) ? wolof : nil,
                .xhosa: languages.contains(.xhosa) ? xhosa : nil,
                .yoruba: languages.contains(.yoruba) ? yoruba : nil,
                .zulu: languages.contains(.zulu) ? zulu : nil
            ].compactMapValues { $0 }
        )
    }
}
